version: 0.2
phases:
  install:
    commands:
      - bash codebuild.sh install_phase
  build:
    commands:
      - bash codebuild.sh build_phase
  post_build:
    commands:
      - bash codebuild.sh post_build_phase
